//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hick.PatientLookUp.ASPX {
    
    
    public partial class Recordaccess {
        
        /// <summary>
        /// ucRecordaccess1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Hick.PatientLookUp.UserControls.UCRecordaccess ucRecordaccess1;
    }
}
